import type { Attributes } from '../types.js';

/**
 * Signature strengths and weaknesses for well-known players, so that stars feel like
 * themselves (Haaland's finishing, Doku's dribbling). Everything else is generated from
 * the player's position and ability rating. These are Touchline's estimates.
 */
export interface Trait {
  foot?: 'L' | 'R' | 'B';
  attrs?: Partial<Attributes>;
}

export const TRAITS: Record<string, Trait> = {
  'Erling Haaland': { foot: 'L', attrs: { finishing: 20, strength: 19, offTheBall: 19, heading: 17, pace: 17, acceleration: 16, composure: 17, dribbling: 13 } },
  'Bukayo Saka': { foot: 'L', attrs: { dribbling: 17, crossing: 17, technique: 17, flair: 16, workRate: 17, finishing: 15, pace: 16 } },
  'Cole Palmer': { foot: 'L', attrs: { composure: 20, technique: 18, passing: 17, creativity: 18, finishing: 16, longShots: 16, setPieces: 17, pace: 12 } },
  'Declan Rice': { foot: 'R', attrs: { tackling: 17, stamina: 18, workRate: 18, passing: 16, positioning: 17, setPieces: 16, teamwork: 18 } },
  'William Saliba': { foot: 'R', attrs: { tackling: 17, marking: 17, positioning: 18, composure: 18, pace: 16, strength: 16 } },
  'Gabriel Magalhães': { foot: 'L', attrs: { heading: 18, jumping: 18, strength: 18, aggression: 16 } },
  'Martin Ødegaard': { foot: 'L', attrs: { passing: 18, creativity: 18, technique: 18, setPieces: 16, pace: 12 } },
  'Viktor Gyökeres': { foot: 'R', attrs: { strength: 18, finishing: 17, pace: 16, offTheBall: 16 } },
  'David Raya': { attrs: { handling: 16, reflexes: 17, passing: 15, oneOnOnes: 16 } },
  'Eberechi Eze': { foot: 'R', attrs: { dribbling: 17, technique: 17, flair: 17, longShots: 15 } },
  'Rodri': { foot: 'R', attrs: { passing: 18, decisions: 19, positioning: 18, composure: 18, teamwork: 18, pace: 11 } },
  'Jérémy Doku': { foot: 'R', attrs: { dribbling: 19, acceleration: 19, pace: 18, agility: 18, flair: 18, finishing: 11, crossing: 12 } },
  'Rayan Cherki': { foot: 'B', attrs: { technique: 19, flair: 19, dribbling: 18, passing: 16, workRate: 10 } },
  'Phil Foden': { foot: 'L', attrs: { technique: 18, dribbling: 17, finishing: 16, flair: 17, longShots: 16 } },
  'Joško Gvardiol': { foot: 'L', attrs: { strength: 16, passing: 15, positioning: 16 } },
  'Rayan Aït-Nouri': { foot: 'L', attrs: { dribbling: 16, pace: 16 } },
  'Gianluigi Donnarumma': { attrs: { reflexes: 18, oneOnOnes: 18, aerialAbility: 17, handling: 15 } },
  'Antoine Semenyo': { foot: 'R', attrs: { pace: 16, strength: 16, finishing: 15, longShots: 15 } },
  'Florian Wirtz': { foot: 'R', attrs: { technique: 19, creativity: 19, dribbling: 17, passing: 17, decisions: 17, flair: 18 } },
  'Virgil van Dijk': { foot: 'R', attrs: { heading: 18, jumping: 17, positioning: 18, composure: 18, strength: 17, marking: 17, pace: 13 } },
  'Alexander Isak': { foot: 'R', attrs: { finishing: 18, dribbling: 17, technique: 17, composure: 17, pace: 16 } },
  'Alexis Mac Allister': { foot: 'R', attrs: { passing: 17, decisions: 17, setPieces: 16, longShots: 15 } },
  'Ryan Gravenberch': { foot: 'R', attrs: { dribbling: 16, passing: 16, composure: 17, tackling: 15 } },
  'Dominik Szoboszlai': { foot: 'R', attrs: { longShots: 17, stamina: 18, setPieces: 17, workRate: 17 } },
  'Jeremie Frimpong': { foot: 'R', attrs: { pace: 19, acceleration: 19, crossing: 15, tackling: 12 } },
  'Milos Kerkez': { foot: 'L', attrs: { stamina: 17, crossing: 15, aggression: 15 } },
  'Alisson Becker': { attrs: { reflexes: 18, oneOnOnes: 18, handling: 17, passing: 15 } },
  'Hugo Ekitike': { foot: 'R', attrs: { dribbling: 16, technique: 16, pace: 16 } },
  'Bruno Fernandes': { foot: 'R', attrs: { passing: 17, creativity: 18, longShots: 17, setPieces: 18, workRate: 17, determination: 18 } },
  'Bryan Mbeumo': { foot: 'L', attrs: { finishing: 16, setPieces: 15, offTheBall: 16, workRate: 16 } },
  'Matheus Cunha': { foot: 'R', attrs: { dribbling: 17, technique: 16, longShots: 15, aggression: 15 } },
  'Lisandro Martínez': { foot: 'L', attrs: { aggression: 18, passing: 15, determination: 18, jumping: 12 } },
  'Moisés Caicedo': { foot: 'R', attrs: { tackling: 18, stamina: 18, workRate: 19, anticipation: 17 } },
  'Enzo Fernández': { foot: 'R', attrs: { passing: 17, longShots: 16, creativity: 16 } },
  'Pedro Neto': { foot: 'L', attrs: { pace: 17, dribbling: 17, crossing: 16 } },
  'Estêvão': { foot: 'L', attrs: { dribbling: 18, flair: 18, technique: 17, acceleration: 17 } },
  'Reece James': { foot: 'R', attrs: { crossing: 16, strength: 16, setPieces: 15, injuryProneness: 18 } },
  'Levi Colwill': { foot: 'L', attrs: { passing: 16, composure: 16 } },
  'Bruno Guimarães': { foot: 'R', attrs: { passing: 16, tackling: 16, workRate: 17, technique: 16 } },
  'Morgan Gibbs-White': { foot: 'R', attrs: { dribbling: 16, passing: 15, creativity: 16, workRate: 16 } },
  'Murillo': { foot: 'L', attrs: { pace: 16, strength: 16, passing: 15 } },
  'Chris Wood': { foot: 'R', attrs: { heading: 17, strength: 18, finishing: 15, pace: 10 } },
  'Adam Wharton': { foot: 'L', attrs: { passing: 18, decisions: 16, composure: 16 } },
  'Jean-Philippe Mateta': { foot: 'R', attrs: { strength: 17, finishing: 15, heading: 15 } },
  'Dean Henderson': { attrs: { reflexes: 17, oneOnOnes: 16 } },
  'Mohammed Kudus': { foot: 'L', attrs: { dribbling: 18, agility: 17, strength: 15, flair: 17 } },
  'Pedro Porro': { foot: 'R', attrs: { crossing: 17, setPieces: 16, passing: 15 } },
  'Micky van de Ven': { foot: 'L', attrs: { pace: 20, acceleration: 18, tackling: 16 } },
  'James Maddison': { foot: 'R', attrs: { setPieces: 18, creativity: 17, passing: 16, longShots: 16 } },
  'Sandro Tonali': { foot: 'R', attrs: { passing: 16, tackling: 16, stamina: 18, workRate: 17 } },
  'Destiny Udogie': { foot: 'L', attrs: { pace: 16, stamina: 16 } },
  'Dejan Kulusevski': { foot: 'L', attrs: { strength: 15, crossing: 15, dribbling: 15 } },
  'Andy Robertson': { foot: 'L', attrs: { crossing: 17, stamina: 17, workRate: 18, pace: 13 } },
  'Alejandro Garnacho': { foot: 'R', attrs: { pace: 17, dribbling: 16, finishing: 13 } },
  'Dominic Calvert-Lewin': { foot: 'R', attrs: { heading: 18, jumping: 17, injuryProneness: 17 } },
  'Granit Xhaka': { foot: 'L', attrs: { passing: 17, longShots: 15, aggression: 17, pace: 9 } },
  'Lewis Dunk': { foot: 'R', attrs: { heading: 17, passing: 15, pace: 8 } },
  'James Tarkowski': { foot: 'R', attrs: { heading: 17, tackling: 16, pace: 9 } },
  'Jordan Henderson': { foot: 'R', attrs: { workRate: 17, passing: 15, pace: 8 } },
  'Jordan Pickford': { attrs: { reflexes: 17, passing: 14, aggression: 15 } },
  'Kaoru Mitoma': { foot: 'R', attrs: { dribbling: 18, agility: 17, acceleration: 16 } },
  'Jarrad Branthwaite': { foot: 'L', attrs: { heading: 16, strength: 16, pace: 15 } },
  'Iliman Ndiaye': { foot: 'R', attrs: { dribbling: 17, agility: 16, flair: 16 } },
  'Ismaïla Sarr': { foot: 'R', attrs: { pace: 18, acceleration: 17 } },
  'Xavi Simons': { foot: 'R', attrs: { dribbling: 17, technique: 17, flair: 17 } },
  'Harry Maguire': { foot: 'R', attrs: { heading: 18, strength: 17, pace: 8 } },
  'Nick Pope': { attrs: { reflexes: 17, aerialAbility: 16, passing: 10 } },
  'Anthony Elanga': { foot: 'R', attrs: { pace: 18, acceleration: 18 } },
  'Max Dowman': { foot: 'L', attrs: { dribbling: 15, flair: 16, technique: 14 } },
};
